---
title: "Extracting APPGs"
output: html_notebook
---

Load libraries
```{r}
library(dplyr)
library(rvest)
library(tibble)
library(tidyverse)
library(xml2)
```

Set base URL and get HTML content with curl
```{r}
base_url <- "https://publications.parliament.uk/pa/cm/cmallparty/250618/contents.htm"
cmd <- paste("curl -A 'Mozilla/5.0'", base_url)
html <- system(cmd, intern = TRUE)
head(html, 3)
```

Parse HTML text - necessary code?
```{r}
html_text <- html %>% 
   paste(collapse = "\n") %>% 
   read_html()
```

```{r}
# Find hrefs
links <- html_text %>% 
   html_nodes("a") %>% 
   html_attr("href") 
       
# Preview the first five hrefs
head(links)
```

```{r}
# Save as tibble and preview
url_tibble <- tibble(url = links) 
head(url_tibble)
```

Filter out non-APPG hrefs (consistent between versions)
```{r}

# Add column for row number and filter NA rows
url_tibble <- url_tibble %>% 
   mutate(row_id = row_number()) %>% 
   drop_na() %>% 
   mutate(
      version = "250618", 
      name = NA
   )

# Get target rows (rows before and after which to filter out)
target_row <- url_tibble %>% 
   filter(url == "#subject-groups")

target_row_2 <- url_tibble %>% 
   filter(url == "http://www.parliament.uk/site-information/azindex/")

filtered_urls <- url_tibble %>% 
   filter(row_id > target_row$row_id & row_id < target_row_2$row_id)
```


Create new dataframe. For each URL, add as new row
```{r}

base_url2 <- "https://publications.parliament.uk/pa/cm/cmallparty/250618/"

for (x in 1:length(filtered_urls$row_id)) {
   new_row <- paste0(base_url2, as.character(filtered_urls$url[x]), sep="")
   filtered_urls$url[x] <- rbind(new_row, filtered_urls$url[x])
}

glimpse(filtered_urls)
```


```{r}
url2 <- pluck(filtered_urls$url[1])
cmd <- paste("curl -A 'Mozilla/5.0'", url2)
new_html <- system(cmd, intern = TRUE)
head(new_html)
```

```{r}
new_html_text <- new_html %>% 
   paste(collapse = "\n") %>% 
   read_html()
```

Extract information from page tables


```{r}
tables <- html_table(new_html_text, fill = TRUE)
length(tables)

tables[[1]]
tables[[2]]
tables[[3]]
tables[[4]]
tables[[5]]
tables[[6]]
```

Interested in: version, name, description, category, chair name, chair party, benefit source, benefit value



```{r}
appg_info <- data.frame(
   version = character(), 
   name = character(), 
   description = character(), 
   chair_name = character(),
   chair_party = character(), 
   benefit_source = character(),
   benefit_value = character()
)
```

```{r}
appg_info <- bind_rows(appg_info, tibble(
   version = url_tibble$version[1],
   name = tables[[1]]$X2[[1]], 
   description = tables[[1]]$X2[[2]],
   chair_name = tables[[2]]$X2[[3]],
   chair_party = tables[[2]]$X3[[3]],
   benefit_source = tables[[6]]$X1[[3]], 
   benefit_value = tables[[6]]$X3[[3]]
))
```



```{r}
url2 <- pluck(filtered_urls$url[2])
cmd <- paste("curl -A 'Mozilla/5.0'", url2)
new_html <- system(cmd, intern = TRUE)
head(new_html)

new_html_text <- new_html %>% 
   paste(collapse = "\n") %>% 
   read_html()

tables <- html_table(new_html_text, fill = TRUE)

appg_info <- bind_rows(appg_info, tibble(
   version = url_tibble$version[1],
   name = tables[[1]]$X2[[1]], 
   description = tables[[1]]$X2[[2]],
   chair_name = tables[[2]]$X2[[3]],
   chair_party = tables[[2]]$X3[[3]],
   benefit_source = pluck(tables, 6, "X1", 3,  .default =  NA),
   benefit_value = pluck(tables, 6, "X3", 3,  .default =  NA)
))
```
